li = [
    'Facebook',
    'Google',
    'LinkedIn',
    'Apple',
    'Amazon',
    'Robinhood',
    'Miscrosoft',
    'Bloomberg',
    'Lyft',
    'Uber',
    'Twitter',
    'Hulu',
    'Zillow',
    'Yelp',
    'Dropbox',
    'SAP',
    'Nordstrom',
    'Moz',
    'PicMonkey',
    'Godaddy',
    'Groupon',
    'Saleforce',
    'Redfin',
    'Qumulo',
    'F5 Network',
    'Adobe',
    'EMC',
    'Asana',
    'Docker',
    'WhatsApp',
    'Intel',
    'Quip',
    'Houzz',
    'Square',
    'Snapchat',
    'Expedia',
    'Quora',
    'Inded',
    'Tableau',
    'Tapad',
    'Palantir',
    'Pinterest',
    'Stripe',
    'TwoSigma',
    'Triapdvisor',
    'PocketGem',
    'Coursera',
    'Github',
    'Udacity',
    'Fitbit',
    'EA',
    'Oracle',
    'Zynga',
    'eBay',
    'Paypal',
    'Venmo',
    'Trulia',
    'Medallia',
    'Spokeo',
    'NetApp',
    'Red Hat',
    'Appfolio',
    'IXL',
    'Cerner',
    'Vmware',
    'Nutanix',
    'Altera',
    'Commvault',
    'IBG',
    'Nest',
    'Cloudera',
    'Wayfair',
    'Carfax',
    'Quantcast',
    'Guidwire',
    'Spotify',
    'FactSet',
    'Zeneftis',
    'RocketFuel',
    'Thumbtack',
    'Cisco',
    'BOA',
    'Walmart',
    'Factest',
    'MathsWork',
    'Swift Navigation',
    'SpiceWork',
    'Hitachi',
    'Turn',
    'Visa',
    'Amplitude',
    'Intuid',
    'xAd',
    'Pure Stroage',
    'IBM',
    'Wish',
]

def get_companies():
    companies = set()
    for c in li:
        companies.add(c.lower())
        companies.add(c)
        companies.add(c.capitalize())

    return companies
